DATASET:
  DATA_SOURCE: 'ggl'
  DATA_ROOT: 'data/MFR/'
  SCENES: None  # should be a list [] or None. If none, use all scenes.
  ESTIMATED_DEPTH: None  # To load estimated depth map, provide the suffix to the depth files, e.g. 'dptnyu', 'dptkiti'
  AUGMENTATION_TYPE: None
  HEIGHT: 256
  WIDTH: 256
  MIN_OVERLAP_SCORE: 0.0  # [train only] discard data with overlap_score < min_overlap_score
  MAX_OVERLAP_SCORE: 1.0  # [train only] discard data with overlap_score < min_overlap_score
